apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/traefik/crds/
  - traefik.yaml
  - traefik-ingress.yaml
  - traefik-ingressclass.yaml
  - traefik-rbac.yaml
  - traefik-service.yaml
