apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-upgrade.yaml
  - talos-upgrade.yaml
  - upstream.yaml

  - https://github.com/home-operations/tuppr/config/crd?ref=0.0.47
